"""обавление столбца account_number в таблицу clients

Revision ID: 5be4ecdc8841
Revises: 
Create Date: 2025-02-13 16:14:27.115756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be4ecdc8841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('postal_address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('owner_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('connected_power', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('passport_data', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('inn', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('snils', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('connection_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('power_source', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('additional_info', sa.String(), nullable=True))
    op.drop_index('ix_clients_name', table_name='clients')
    op.create_index(op.f('ix_clients_account_number'), 'clients', ['account_number'], unique=True)
    op.drop_column('clients', 'name')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_account_number'), table_name='clients')
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.drop_column('clients', 'additional_info')
    op.drop_column('clients', 'power_source')
    op.drop_column('clients', 'connection_date')
    op.drop_column('clients', 'snils')
    op.drop_column('clients', 'inn')
    op.drop_column('clients', 'passport_data')
    op.drop_column('clients', 'connected_power')
    op.drop_column('clients', 'phone_number')
    op.drop_column('clients', 'owner_name')
    op.drop_column('clients', 'postal_address')
    op.drop_column('clients', 'account_number')
    # ### end Alembic commands ###
